### ISSUE TITLE
Support IPIP-417 (Delegated Peer lookups)

### ISSUE THREAD

**Issue by BigLep** [libp2p/js-http-v1-content-routing#25]
## Done Criteria
[IPIP-417 (Delegated Peer lookups)](https://github.com/ipfs/specs/pull/417) support, meaning could delegate peer lookups with another HTTP /routing/v1 implementation like Kubo

## Why Important
This is needed for the Helia reliable retrieval golden path scenario: https://github.com/ipfs/helia/issues/255

**Comment by achingbrain** [comment]
This is an implementation of the libp2p [ContentRouting](https://libp2p.github.io/js-libp2p/interfaces/_libp2p_interface.content_routing.ContentRouting.html) interface.

Peer lookups would be done by an implementation of the libp2p [PeerRouting](https://libp2p.github.io/js-libp2p/interfaces/_libp2p_interface.peer_routing.PeerRouting.html) interface so this isn't the place to do that.

We might end up getting `@helia/delegated-routing-v1-http-api` to make implementations of both of these interfaces available after all since passing the same instance as [contentRouters](https://libp2p.github.io/js-libp2p/interfaces/libp2p.index.Libp2pInit.html#contentRouters) and [peerRouters](https://libp2p.github.io/js-libp2p/interfaces/libp2p.index.Libp2pInit.html#peerRouters) is a bit icky.
